package fr.legrain.SupportAbon.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import fr.legrain.abonnement.dao.TaAbonnement;
import fr.legrain.abonnement.dao.TaRAbonnement;
import fr.legrain.articles.dao.TaArticle;
import fr.legrain.articles.dao.TaTSupport;
import fr.legrain.documents.dao.TaLFacture;
import fr.legrain.documents.dao.TaRDocument;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_OPTION_ABON")
@SequenceGenerator(name = "GEN_OPTION_ABON", sequenceName = "NUM_ID_OPTION_ABON", allocationSize = 1)

public  class TaOptionAbon implements java.io.Serializable {

   
	private Integer idOptionAbon;
	private String optionAbon;
    private TaArticle taArticle;
    private TaTSupport taTArticle;

    
    private Set<TaROptionAbon> taROptionAbons = new HashSet<TaROptionAbon>(0);

	
	public TaOptionAbon() {
	}

	public TaOptionAbon(Integer idOptionAbon) {
		this.idOptionAbon = idOptionAbon;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_OPTION_ABON")
	@Column(name = "ID_OPTION_ABON", unique = true)
	public Integer getIdOptionAbon() {
		return this.idOptionAbon;
	}

	public void setIdOptionAbon(Integer idOptionAbon) {
		this.idOptionAbon = idOptionAbon;
	}

	@Column(name = "OPTION_ABON")
	@LgrHibernateValidated(champ = "OPTION_ABON",table = "TA_OPTION_ABON",clazz = TaOptionAbon.class)
	public String getOptionAbon() {
		return this.optionAbon;
	}

	public void setOptionAbon(String optionAbon) {
		this.optionAbon = optionAbon;
	}

	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champ = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}


	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_T_ARTICLE")
	@LgrHibernateValidated(champ = "ID_T_ARTICLE",table = "TA_T_ARTICLE",clazz = TaTSupport.class)
	public TaTSupport getTaTArticle() {
		return taTArticle;
	}

	public void setTaTArticle(TaTSupport taTArticle) {
		this.taTArticle = taTArticle;
	}
	

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taOptionAbon")
	public Set<TaROptionAbon> getTaROptionAbons() {
		return this.taROptionAbons;
	}

	public void setTaROptionAbons(Set<TaROptionAbon> taROptionAbons) {
		this.taROptionAbons = taROptionAbons;
	}


	
}
