package fr.legrain.SupportAbon.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import fr.legrain.abonnement.dao.TaAbonnement;
import fr.legrain.abonnement.dao.TaRAbonnement;
import fr.legrain.articles.dao.TaArticle;
import fr.legrain.articles.dao.TaTSupport;
import fr.legrain.documents.dao.TaLFacture;
import fr.legrain.documents.dao.TaRDocument;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_R_OPTION_ABON")
@SequenceGenerator(name = "GEN_R_OPTION_ABON", sequenceName = "NUM_ID_R_OPTION_ABON", allocationSize = 1)

public  class TaROptionAbon implements java.io.Serializable {

   
	private Integer idROptionAbon;
    private TaSupportAbon taSupportAbon;
    private TaOptionAbon taOptionAbon;
	
    
	public TaROptionAbon() {
	}

	public TaROptionAbon(Integer idROptionAbon) {
		this.idROptionAbon = idROptionAbon;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_R_OPTION_ABON")
	@Column(name = "ID_R_OPTION_ABON", unique = true)
	public Integer getIdROptionAbon() {
		return this.idROptionAbon;
	}

	public void setIdROptionAbon(Integer idROptionAbon) {
		this.idROptionAbon = idROptionAbon;
	}

	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_SUPPORT_ABON")
	@LgrHibernateValidated(champ = "ID_SUPPORT_ABON",table = "TA_SUPPORT_ABON",clazz = TaSupportAbon.class)
	public TaSupportAbon getTaSupportAbon() {
		return taSupportAbon;
	}

	public void setTaSupportAbon(TaSupportAbon taSupportAbon) {
		this.taSupportAbon = taSupportAbon;
	}


	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_OPTION_ABON")
	@LgrHibernateValidated(champ = "ID_OPTION_ABON",table = "TA_OPTION_ABON",clazz = TaOptionAbon.class)
	public TaOptionAbon getTaOptionAbon() {
		return taOptionAbon;
	}

	public void setTaOptionAbon(TaOptionAbon taOptionAbon) {
		this.taOptionAbon = taOptionAbon;
	}
	
	
}
