package fr.legrain.lgrBackup.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.SupportAbonLegrain.dao.TaIpFixe;
import fr.legrain.SupportAbonLegrain.dao.TaRegistrar;
import fr.legrain.SupportAbonLegrain.dao.TaServeur;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_LGR_BACKUP")
public  class TaLgrBackup extends TaSupportAbon implements java.io.Serializable {


	private Integer nbPoste;
	
	public TaLgrBackup() {
	}

	


public TaLgrBackup( Integer nbPoste) {
		super();
		this.nbPoste = nbPoste;
	}



@Column(name = "NB_POSTE")
@LgrHibernateValidated(champ = "NB_POSTE",table = "TA_LGR_BACKUP",clazz = TaLgrBackup.class)
public Integer getNbPoste() {
	return nbPoste;
}



public void setNbPoste(Integer nbPoste) {
	this.nbPoste = nbPoste;
}



}
