package fr.legrain.visualisation.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import fr.legrain.documents.dao.TaFacture;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
@Table(name = "TA_VISUALISATION")
@SequenceGenerator(name = "GEN_VISUALISATION", sequenceName = "NUM_ID_VISUALISATION", allocationSize = 1)
@NamedQueries(value = { 
		@NamedQuery(name=TaVisualisation.QN.FIND_BY_MODULE, 
				query="select a from TaVisualisation a where upper(a.module) = ? order by a.codeRequete")
		})
public class TaVisualisation implements java.io.Serializable {
	
	public static class QN {
		public static final String FIND_BY_MODULE = "TaVisualisation.findByModule";
	}
	
	private int id;
    private String codeRequete;
    private String requete;
    private String champs;
    private String titreChamps;
    private String tailleChamps;
    private String module;
    private String impression;
    private String identifiant;
    private String idEditeur;
    private String idPlugin;
    private String clauseWhere;
    private String groupby;
    private String clauseHaving;
    private Integer proc;
    private String param;
    private String typesRetour;
    private String totaux;
    private String queryLang;
    private String classeRecherche;
//  private String quiCreeAdresse;
//  private Date quandCreeAdresse; 
//  private String quiModifAdresse;
//  private Date quandModifAdresse; 
//  private String ipAcces;
//  private Integer versionOb;

	public TaVisualisation() {
	}

	public TaVisualisation(int id, String codeRequete, String requete,
			String champs, String titreChamps, String tailleChamps,
			String module, String impression, String identifiant,
			String idEditeur, String idPlugin, String clauseWhere,
			String groupby, String clauseHaving, Integer proc, String param,
			String typesRetour, String totaux, String queryLang, String classeRecherche) {
		super();
		this.id = id;
		this.codeRequete = codeRequete;
		this.requete = requete;
		this.champs = champs;
		this.titreChamps = titreChamps;
		this.tailleChamps = tailleChamps;
		this.module = module;
		this.impression = impression;
		this.identifiant = identifiant;
		this.idEditeur = idEditeur;
		this.idPlugin = idPlugin;
		this.clauseWhere = clauseWhere;
		this.groupby = groupby;
		this.clauseHaving = clauseHaving;
		this.proc = proc;
		this.param = param;
		this.typesRetour = typesRetour;
		this.totaux = totaux;
		this.queryLang = queryLang;
		this.classeRecherche = classeRecherche;
	}

	public TaVisualisation(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_VISUALISATION")
	@Column(name = "ID", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CODE_REQUETE", length = 255)
	@LgrHibernateValidated(champ = "CODE_REQUETE",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getCodeRequete() {
		return codeRequete;
	}

	public void setCodeRequete(String codeRequete) {
		this.codeRequete = codeRequete;
	}

	@Column(name = "REQUETE", length = 2000)
	@LgrHibernateValidated(champ = "REQUETE",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getRequete() {
		return requete;
	}

	public void setRequete(String requete) {
		this.requete = requete;
	}

	@Column(name = "CHAMPS", length = 2000)
	@LgrHibernateValidated(champ = "CHAMPS",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getChamps() {
		return champs;
	}

	public void setChamps(String champs) {
		this.champs = champs;
	}

	@Column(name = "TITRE_CHAMPS", length = 2000)
	@LgrHibernateValidated(champ = "TITRE_CHAMPS",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getTitreChamps() {
		return titreChamps;
	}

	public void setTitreChamps(String titreChamps) {
		this.titreChamps = titreChamps;
	}

	@Column(name = "TAILLE_CHAMPS", length = 255)
	@LgrHibernateValidated(champ = "TAILLE_CHAMPS",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getTailleChamps() {
		return tailleChamps;
	}

	public void setTailleChamps(String tailleChamps) {
		this.tailleChamps = tailleChamps;
	}

	@Column(name = "MODULE", length = 255)
	@LgrHibernateValidated(champ = "MODULE",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getModule() {
		return module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	@Column(name = "IMPRESSION", length = 255)
	@LgrHibernateValidated(champ = "IMPRESSION",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getImpression() {
		return impression;
	}

	public void setImpression(String impression) {
		this.impression = impression;
	}

	@Column(name = "IDENTIFIANT", length = 255)
	@LgrHibernateValidated(champ = "IDENTIFIANT",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getIdentifiant() {
		return identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	@Column(name = "ID_EDITEUR", length = 255)
	@LgrHibernateValidated(champ = "ID_EDITEUR",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getIdEditeur() {
		return idEditeur;
	}

	public void setIdEditeur(String idEditeur) {
		this.idEditeur = idEditeur;
	}

	@Column(name = "ID_PLUGIN", length = 255)
	@LgrHibernateValidated(champ = "ID_PLUGIN",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getIdPlugin() {
		return idPlugin;
	}

	public void setIdPlugin(String idPlugin) {
		this.idPlugin = idPlugin;
	}

	@Column(name = "CLAUSE_WHERE", length = 2000)
	@LgrHibernateValidated(champ = "CLAUSE_WHERE",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getClauseWhere() {
		return clauseWhere;
	}

	public void setClauseWhere(String clauseWhere) {
		this.clauseWhere = clauseWhere;
	}

	@Column(name = "GROUPBY", length = 2000)
	@LgrHibernateValidated(champ = "GROUPBY",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getGroupby() {
		return groupby;
	}

	public void setGroupby(String groupby) {
		this.groupby = groupby;
	}

	@Column(name = "CLAUSE_HAVING", length = 2000)
	@LgrHibernateValidated(champ = "CLAUSE_HAVING",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getClauseHaving() {
		return clauseHaving;
	}

	public void setClauseHaving(String clauseHaving) {
		this.clauseHaving = clauseHaving;
	}

	@Column(name = "PROC")
	@LgrHibernateValidated(champ = "PROC",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public Integer getProc() {
		return proc;
	}

	public void setProc(Integer proc) {
		this.proc = proc;
	}

	@Column(name = "PARAM", length = 255)
	@LgrHibernateValidated(champ = "PARAM",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getParam() {
		return param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "TYPES_RETOUR", length = 255)
	@LgrHibernateValidated(champ = "TYPES_RETOUR",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getTypesRetour() {
		return typesRetour;
	}

	public void setTypesRetour(String typesRetour) {
		this.typesRetour = typesRetour;
	}

	@Column(name = "TOTAUX", length = 255)
	@LgrHibernateValidated(champ = "TOTAUX",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getTotaux() {
		return totaux;
	}

	public void setTotaux(String totaux) {
		this.totaux = totaux;
	}
	
	@Column(name = "QUERY_LANG", length = 50)
	@LgrHibernateValidated(champ = "QUERY_LANG",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getQueryLang() {
		return queryLang;
	}

	public void setQueryLang(String queryLang) {
		this.queryLang = queryLang;
	}
	
	@Column(name = "CLASSE_RECHERCHE", length = 255)
	@LgrHibernateValidated(champ = "CLASSE_RECHERCHE",table = "TA_VISUALISATION",clazz = TaVisualisation.class)
	public String getClasseRecherche() {
		return classeRecherche;
	}

	public void setClasseRecherche(String classeRecherche) {
		this.classeRecherche = classeRecherche;
	}

}
