package fr.legrain.saisieCaisse.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.documents.dao.TaTPaiement;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;

/**
 * TaEtablissement generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_ETABLISSEMENT")
@SequenceGenerator(name = "GEN_ETABLISSEMENT", sequenceName = "NUM_ID_ETABLISSEMENT", allocationSize = 1)
public class TaEtablissement implements java.io.Serializable {

	private int idEtablissement;
	private String version;
	private String nomEtablissement;
	private String contact;
	private TaTPaiement taTPaiement;
	private String quiCreeEtablissement;
	private Date quandCreeEtablissement;
	private String quiModifEtablissement;
	private Date quandModifEtablissement;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaOperation> taOperations = new HashSet<TaOperation>(0);
	private Set<TaDepot> taDepots = new HashSet<TaDepot>(0);

	public TaEtablissement() {
	}

	public TaEtablissement(int idEtablissement) {
		this.idEtablissement = idEtablissement;
	}

	public TaEtablissement(int idEtablissement, String nomEtablissement,
			String contact, String quiCreeEtablissement,
			Date quandCreeEtablissement, String quiModifEtablissement,
			Date quandModifEtablissement, String ipAcces, Integer versionObj,
			Set<TaOperation> taOperations,Set<TaDepot> taDepots, TaTPaiement taTPaiement) {
		this.idEtablissement = idEtablissement;
		this.nomEtablissement = nomEtablissement;
		this.contact = contact;
		this.quiCreeEtablissement = quiCreeEtablissement;
		this.quandCreeEtablissement = quandCreeEtablissement;
		this.quiModifEtablissement = quiModifEtablissement;
		this.quandModifEtablissement = quandModifEtablissement;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taOperations = taOperations;
		this.taDepots = taDepots;
		this.taTPaiement = taTPaiement;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_ETABLISSEMENT")
	@Column(name = "ID_ETABLISSEMENT", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_ETABLISSEMENT",table = "TA_ETABLISSEMENT",clazz = TaEtablissement.class)
	public int getIdEtablissement() {
		return this.idEtablissement;
	}

	public void setIdEtablissement(int idEtablissement) {
		this.idEtablissement = idEtablissement;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "NOM_ETABLISSEMENT", length = 100)
	@LgrHibernateValidated(champ = "NOM_ETABLISSEMENT",table = "TA_ETABLISSEMENT",clazz = TaEtablissement.class)
	public String getNomEtablissement() {
		return this.nomEtablissement;
	}

	public void setNomEtablissement(String nomEtablissement) {
		this.nomEtablissement = nomEtablissement;
	}


	@Column(name = "CONTACT", length = 100)
	@LgrHibernateValidated(champ = "CONTACT",table = "TA_ETABLISSEMENT",clazz = TaEtablissement.class)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_T_PAIEMENT")
	@LgrHibernateValidated(champ = "ID_T_PAIEMENT",table = "TA_ETABLISSEMENT",clazz = TaTPaiement.class)
	public TaTPaiement getTaTPaiement() {
		return this.taTPaiement;
	}

	public void setTaTPaiement(TaTPaiement taTPaiement) {
		this.taTPaiement = taTPaiement;
	}
	
	@Column(name = "QUI_CREE_ETABLISSEMENT", length = 50)
	public String getQuiCreeEtablissement() {
		return this.quiCreeEtablissement;
	}

	public void setQuiCreeEtablissement(String quiCreeEtablissement) {
		this.quiCreeEtablissement = quiCreeEtablissement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_ETABLISSEMENT", length = 19)
	public Date getQuandCreeEtablissement() {
		return this.quandCreeEtablissement;
	}

	public void setQuandCreeEtablissement(Date quandCreeEtablissement) {
		this.quandCreeEtablissement = quandCreeEtablissement;
	}

	@Column(name = "QUI_MODIF_ETABLISSEMENT", length = 50)
	public String getQuiModifEtablissement() {
		return this.quiModifEtablissement;
	}

	public void setQuiModifEtablissement(String quiModifEtablissement) {
		this.quiModifEtablissement = quiModifEtablissement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_ETABLISSEMENT", length = 19)
	public Date getQuandModifEtablissement() {
		return this.quandModifEtablissement;
	}

	public void setQuandModifEtablissement(Date quandModifEtablissement) {
		this.quandModifEtablissement = quandModifEtablissement;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taEtablissement")
	public Set<TaOperation> getTaOperations() {
		return this.taOperations;
	}

	public void setTaOperations(Set<TaOperation> taOperations) {
		this.taOperations = taOperations;
	}


	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taEtablissement")
	public Set<TaDepot> getTaDepots() {
		return taDepots;
	}

	public void setTaDepots(Set<TaDepot> taDepots) {
		this.taDepots = taDepots;
	}



 
}
