package fr.legrain.saisieCaisse.dao;

// Generated 2 juin 2009 14:13:00 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.gestCom.Appli.LgrHibernateValidated;

/**
 * TaTOperation generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_T_OPERATION", uniqueConstraints = @UniqueConstraint(columnNames = "CODE_T_OPERATION"))
@SequenceGenerator(name = "GEN_T_OPERATION", sequenceName = "NUM_ID_T_OPERATION", allocationSize = 1)
public class TaTOperation implements java.io.Serializable {

	private int idTOperation;
	private String version;
	private String codeTOperation;
	private String liblTOperation;
	private String quiCreeTOperation;
	private Date quandCreeTOperation;
	private String quiModifTOperation;
	private Date quandModifTOperation;
	private String ipAcces;
	private Integer versionObj;
	private Set<TaOperation> taOperations = new HashSet<TaOperation>(0);

	public TaTOperation() {
	}

	public TaTOperation(int idTOperation) {
		this.idTOperation = idTOperation;
	}

	public TaTOperation(int idTOperation,String version, String codeTOperation,
			String liblTOperation, String quiCreeTOperation,
			Date quandCreeTOperation, String quiModifTOperation,
			Date quandModifTOperation, String ipAcces, Integer versionObj,
			Set<TaOperation> taOperations) {
		this.idTOperation = idTOperation;
		this.version = version;
		this.codeTOperation = codeTOperation;
		this.liblTOperation = liblTOperation;
		this.quiCreeTOperation = quiCreeTOperation;
		this.quandCreeTOperation = quandCreeTOperation;
		this.quiModifTOperation = quiModifTOperation;
		this.quandModifTOperation = quandModifTOperation;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
		this.taOperations = taOperations;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_T_OPERATION")
	@Column(name = "ID_T_OPERATION", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_T_OPERATION",table = "TA_T_OPERATION",clazz = TaTOperation.class)
	public int getIdTOperation() {
		return this.idTOperation;
	}

	public void setIdTOperation(int idTOperation) {
		this.idTOperation = idTOperation;
	}

	//@Version
	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "CODE_T_OPERATION", unique = true, length = 20)
	@LgrHibernateValidated(champ = "CODE_T_OPERATION",table = "TA_T_OPERATION",clazz = TaTOperation.class)
	public String getCodeTOperation() {
		return this.codeTOperation;
	}

	public void setCodeTOperation(String codeTOperation) {
		this.codeTOperation = codeTOperation;
	}

	@Column(name = "LIBL_T_OPERATION", length = 100)
	@LgrHibernateValidated(champ = "LIBL_T_OPERATION",table = "TA_T_OPERATION",clazz = TaTOperation.class)
	public String getLiblTOperation() {
		return this.liblTOperation;
	}

	public void setLiblTOperation(String liblTOperation) {
		this.liblTOperation = liblTOperation;
	}

	@Column(name = "QUI_CREE_T_OPERATION", length = 50)
	public String getQuiCreeTOperation() {
		return this.quiCreeTOperation;
	}

	public void setQuiCreeTOperation(String quiCreeTOperation) {
		this.quiCreeTOperation = quiCreeTOperation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_T_OPERATION", length = 19)
	public Date getQuandCreeTOperation() {
		return this.quandCreeTOperation;
	}

	public void setQuandCreeTOperation(Date quandCreeTOperation) {
		this.quandCreeTOperation = quandCreeTOperation;
	}

	@Column(name = "QUI_MODIF_T_OPERATION", length = 50)
	public String getQuiModifTOperation() {
		return this.quiModifTOperation;
	}

	public void setQuiModifTOperation(String quiModifTOperation) {
		this.quiModifTOperation = quiModifTOperation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_T_OPERATION", length = 19)
	public Date getQuandModifTOperation() {
		return this.quandModifTOperation;
	}

	public void setQuandModifTOperation(Date quandModifTOperation) {
		this.quandModifTOperation = quandModifTOperation;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}
	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taTOperation")
	public Set<TaOperation> getTaOperations() {
		return this.taOperations;
	}

	public void setTaOperations(Set<TaOperation> taOperations) {
		this.taOperations = taOperations;
	}


	@Transient
	public boolean equalsPartiel(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TaTOperation other = (TaTOperation) obj;
		if (codeTOperation == null) {
			if (other.codeTOperation != null)
				return false;
		} else if (!codeTOperation.equals(other.codeTOperation))
			return false;
		if (idTOperation != other.idTOperation)
			return false;
		if (liblTOperation == null) {
			if (other.liblTOperation != null)
				return false;
		} else if (!liblTOperation.equals(other.liblTOperation))
			return false;
		return true;
	}


}
