package fr.legrain.dms.dao;

// Generated 4 juin 2009 10:11:38 by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.saisieCaisse.dao.TaDepot;
import fr.legrain.stocks.dao.TaEtatStock;

/**
 * TaStock generated by hbm2java
 */

public interface ITaEtatDms  {

	public String getCodeArticle();

	public void setCodeArticle(String codeArticle);
	

	public String getCodeFamille() ;

	public void setCodeFamille(String codeFamille) ;



	public String getUn1() ;

	public void setUn1(String un1);



	public String getUn2();
	public void setUn2(String un2) ;


	public Integer getMois() ;

	public void setMois(Integer mois) ;



	public Integer getAnnee();
	
	public void setAnnee(Integer annee);



	
	






}
