package fr.legrain.abonnement.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.articles.dao.TaArticle;
import fr.legrain.articles.dao.TaTAbonnement;
import fr.legrain.documents.dao.TaLEcheance;
import fr.legrain.documents.dao.TaLFacture;
import fr.legrain.documents.dao.TaRDocument;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_ABONNEMENT")
@SequenceGenerator(name = "GEN_ABONNEMENT", sequenceName = "NUM_ID_ABONNEMENT", allocationSize = 1)

public class TaAbonnement implements java.io.Serializable {

	public static final String TYPE_DOC = "fr.legrain.abonnement";
	private int idAbonnement;
    private Date dateDebut;
    private Date dateFin;
    private String commentaire;
    private TaArticle taArticle;
    private TaTiers taTiers;
    private TaTAbonnement taTAbonnement;
    private TaSupportAbon taSupportAbon;
    private TaLFacture taLDocument;
	private Integer versionObj;
	private Integer etat=0;
    
	
	private Set<TaLEcheance> taLEcheances = new HashSet<TaLEcheance>(0);
	
	public TaAbonnement() {
	}

	public TaAbonnement(int idAbonnement) {
		this.idAbonnement = idAbonnement;
	}


	public TaAbonnement(int idAbonnement, Date dateDebut, Date dateFin,
			String commentaire, TaArticle taArticle, TaTiers taTiers,
			TaTAbonnement taTAbonnement, TaSupportAbon taSupportAbon,
			TaLFacture taLDocument, Integer versionObj, Integer etat) {
		super();
		this.idAbonnement = idAbonnement;
		this.dateDebut = dateDebut;
		this.dateFin = dateFin;
		this.commentaire = commentaire;
		this.taArticle = taArticle;
		this.taTiers = taTiers;
		this.taTAbonnement = taTAbonnement;
		this.taSupportAbon = taSupportAbon;
		this.taLDocument = taLDocument;
		this.versionObj = versionObj;
		this.etat = etat;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_ABONNEMENT")
	@Column(name = "ID_ABONNEMENT", unique = true)
	public int getIdAbonnement() {
		return this.idAbonnement;
	}

	public void setIdAbonnement(int idAbonnement) {
		this.idAbonnement = idAbonnement;
	}



	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_DEBUT", length = 10)
	public Date getDateDebut() {
		return dateDebut;
	}


	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_FIN", length = 10)
	public Date getDateFin() {
		return dateFin;
	}


	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champ = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_TIERS")
	@LgrHibernateValidated(champ = "ID_TIERS",table = "TA_TIERS",clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_T_ABONNEMENT")
	@LgrHibernateValidated(champ = "ID_T_ABONNEMENT",table = "TA_T_ABONNEMENT",clazz = TaTAbonnement.class)
	public TaTAbonnement getTaTAbonnement() {
		return taTAbonnement;
	}

	public void setTaTAbonnement(TaTAbonnement taTAbonnement) {
		this.taTAbonnement = taTAbonnement;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_SUPPORT_ABON")
	@LgrHibernateValidated(champ = "ID_SUPPORT",table = "TA_SUPPORT",clazz = TaSupportAbon.class)
	public TaSupportAbon getTaSupportAbon() {
		return taSupportAbon;
	}

	public void setTaSupportAbon(TaSupportAbon taSupportAbon) {
		this.taSupportAbon = taSupportAbon;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_L_FACTURE")
	@LgrHibernateValidated(champ = "ID_L_DOCUMENT",table = "TA_L_FACTURE",clazz = TaLFacture.class)
	public TaLFacture getTaLDocument() {
		return taLDocument;
	}

	public void setTaLDocument(TaLFacture taLDocument) {
		this.taLDocument = taLDocument;
	}
	

	@Column(name = "COMMENTAIRE")
	@LgrHibernateValidated(champ = "COMMENTAIRE",table = "TA_ABONNEMENT",clazz = TaAbonnement.class)
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}


	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Column(name = "ETAT")
	public Integer getEtat() {
		return etat;
	}

	public void setEtat(Integer etat) {
		this.etat = etat;
	}


	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "taAbonnement")
	public Set<TaLEcheance> getTaLEcheances() {
		return this.taLEcheances;
	}

	public void setTaLEcheances(Set<TaLEcheance> taLEcheances) {
		this.taLEcheances = taLEcheances;
	}
	
}
