package fr.legrain.updater.dao;

// Generated 14 mai 2009 14:36:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.gestCom.Appli.LgrHibernateValidated;

/**
 * TaMailMaj generated by hbm2java
 */
@Entity
@Table(name = "TA_MAIL_MAJ")
@SequenceGenerator(name = "GEN_MAIL_MAJ", sequenceName = "NUM_ID_MAIL_MAJ", allocationSize = 1)
public class TaMailMaj implements java.io.Serializable {

	private int idMailMaj;
	private String version;
	private String sujetMailMaj;
	private String nomSiteMailMaj;
	private String urlMailMaj;
	private Date faitMailMaj;
	private Integer AFaireMailMaj;
	private String fromMailMaj;
	private Date dateMailMaj;
	private String quiCreeMailMaj;
	private Date quandCreeMailMaj;
	private String quiModifMailMaj;
	private Date quandModifMailMaj;
	private String ipAcces;
	private Integer versionObj;

	public TaMailMaj() {
	}

	public TaMailMaj(int idMailMaj) {
		this.idMailMaj = idMailMaj;
	}

	public TaMailMaj(int idMailMaj, String sujetMailMaj, String nomSiteMailMaj,
			String urlMailMaj, Date faitMailMaj, Integer AFaireMailMaj,
			String fromMailMaj, Date dateMailMaj, String quiCreeMailMaj,
			Date quandCreeMailMaj, String quiModifMailMaj,
			Date quandModifMailMaj, String ipAcces, Integer versionObj) {
		this.idMailMaj = idMailMaj;
		this.sujetMailMaj = sujetMailMaj;
		this.nomSiteMailMaj = nomSiteMailMaj;
		this.urlMailMaj = urlMailMaj;
		this.faitMailMaj = faitMailMaj;
		this.AFaireMailMaj = AFaireMailMaj;
		this.fromMailMaj = fromMailMaj;
		this.dateMailMaj = dateMailMaj;
		this.quiCreeMailMaj = quiCreeMailMaj;
		this.quandCreeMailMaj = quandCreeMailMaj;
		this.quiModifMailMaj = quiModifMailMaj;
		this.quandModifMailMaj = quandModifMailMaj;
		this.ipAcces = ipAcces;
		this.versionObj = versionObj;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_MAIL_MAJ")
	@Column(name = "ID_MAIL_MAJ", unique = true, nullable = false)
	public int getIdMailMaj() {
		return this.idMailMaj;
	}

	public void setIdMailMaj(int idMailMaj) {
		this.idMailMaj = idMailMaj;
	}

//	@Version
	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "SUJET_MAIL_MAJ")
	@LgrHibernateValidated(champ = "SUJET_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public String getSujetMailMaj() {
		return this.sujetMailMaj;
	}

	public void setSujetMailMaj(String sujetMailMaj) {
		this.sujetMailMaj = sujetMailMaj;
	}

	@Column(name = "NOM_SITE_MAIL_MAJ")
	@LgrHibernateValidated(champ = "NOM_SITE_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public String getNomSiteMailMaj() {
		return this.nomSiteMailMaj;
	}

	public void setNomSiteMailMaj(String nomSiteMailMaj) {
		this.nomSiteMailMaj = nomSiteMailMaj;
	}

	@Column(name = "URL_MAIL_MAJ")
	@LgrHibernateValidated(champ = "URL_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public String getUrlMailMaj() {
		return this.urlMailMaj;
	}

	public void setUrlMailMaj(String urlMailMaj) {
		this.urlMailMaj = urlMailMaj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FAIT_MAIL_MAJ", length = 19)
	@LgrHibernateValidated(champ = "FAIT_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public Date getFaitMailMaj() {
		return this.faitMailMaj;
	}

	public void setFaitMailMaj(Date faitMailMaj) {
		this.faitMailMaj = faitMailMaj;
	}

	@Column(name = "A_FAIRE_MAIL_MAJ")
	@LgrHibernateValidated(champ = "A_FAIRE_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public Integer getAFaireMailMaj() {
		return this.AFaireMailMaj;
	}

	public void setAFaireMailMaj(Integer AFaireMailMaj) {
		this.AFaireMailMaj = AFaireMailMaj;
	}

	@Column(name = "FROM_MAIL_MAJ")
	@LgrHibernateValidated(champ = "FROM_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public String getFromMailMaj() {
		return this.fromMailMaj;
	}

	public void setFromMailMaj(String fromMailMaj) {
		this.fromMailMaj = fromMailMaj;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_MAIL_MAJ", length = 10)
	@LgrHibernateValidated(champ = "DATE_MAIL_MAJ",table = "TA_MAIL_MAJ",clazz = TaMailMaj.class)
	public Date getDateMailMaj() {
		return this.dateMailMaj;
	}

	public void setDateMailMaj(Date dateMailMaj) {
		this.dateMailMaj = dateMailMaj;
	}

	@Column(name = "QUI_CREE_MAIL_MAJ", length = 50)
	public String getQuiCreeMailMaj() {
		return this.quiCreeMailMaj;
	}

	public void setQuiCreeMailMaj(String quiCreeMailMaj) {
		this.quiCreeMailMaj = quiCreeMailMaj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE_MAIL_MAJ", length = 19)
	public Date getQuandCreeMailMaj() {
		return this.quandCreeMailMaj;
	}

	public void setQuandCreeMailMaj(Date quandCreeMailMaj) {
		this.quandCreeMailMaj = quandCreeMailMaj;
	}

	@Column(name = "QUI_MODIF_MAIL_MAJ", length = 50)
	public String getQuiModifMailMaj() {
		return this.quiModifMailMaj;
	}

	public void setQuiModifMailMaj(String quiModifMailMaj) {
		this.quiModifMailMaj = quiModifMailMaj;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF_MAIL_MAJ", length = 19)
	public Date getQuandModifMailMaj() {
		return this.quandModifMailMaj;
	}

	public void setQuandModifMailMaj(Date quandModifMailMaj) {
		this.quandModifMailMaj = quandModifMailMaj;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

}
