package fr.legrain.supportNDD.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.SupportAbonLegrain.dao.TaIpFixe;
import fr.legrain.SupportAbonLegrain.dao.TaRegistrar;
import fr.legrain.SupportAbonLegrain.dao.TaServeur;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_NDD")
public  class TaNDD extends TaSupportAbon implements java.io.Serializable {


	private TaServeur taServeur;
	private String nomDomaine;
	private TaRegistrar taRegistrar;
	private TaIpFixe taIpFixe;
	private String idTitulaire;
	private String passeword;
	private String question;
	private String reponse;
	private String authInfo;
	
	public TaNDD() {
	}

	


public TaNDD(TaServeur taServeur, String domaine, TaRegistrar taRegistrar,
			TaIpFixe taIpFixe, String idTitulaire, String passeword,
			String question, String reponse, String authInfo) {
		super();
		this.taServeur = taServeur;
		this.nomDomaine = domaine;
		this.taRegistrar = taRegistrar;
		this.taIpFixe = taIpFixe;
		this.idTitulaire = idTitulaire;
		this.passeword = passeword;
		this.question = question;
		this.reponse = reponse;
		this.authInfo = authInfo;
	}




@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
@JoinColumn(name = "ID_SERVEUR")
@LgrHibernateValidated(champ = "ID_SERVEUR",table = "TA_SERVEUR",clazz = TaServeur.class)
public TaServeur getTaServeur() {
	return taServeur;
}


public void setTaServeur(TaServeur taServeur) {
	this.taServeur = taServeur;
}


@Column(name = "NOM_DOMAINE", length = 255)
@LgrHibernateValidated(champ = "NOM_DOMAINE",table = "TA_NDD",clazz = TaNDD.class)
public String getNomDomaine() {
	return nomDomaine;
}



public void setNomDomaine(String domaine) {
	this.nomDomaine = domaine;
}



@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
@JoinColumn(name = "ID_REGISTRAR")
@LgrHibernateValidated(champ = "ID_REGISTRAR",table = "TA_REGISTRAR",clazz = TaRegistrar.class)
public TaRegistrar getRegistrar() {
	return taRegistrar;
}



public void setRegistrar(TaRegistrar taRegistrar) {
	this.taRegistrar = taRegistrar;
}



@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
@JoinColumn(name = "ID_IP_FIXE")
@LgrHibernateValidated(champ = "ID_IP_FIXE",table = "TA_IP_FIXE",clazz = TaIpFixe.class)
public TaIpFixe getTaIpFixe() {
	return taIpFixe;
}



public void setTaIpFixe(TaIpFixe taIpFixe) {
	this.taIpFixe = taIpFixe;
}



@Column(name = "ID_TITULAIRE", length = 100)
@LgrHibernateValidated(champ = "ID_TITULAIRE",table = "TA_NDD",clazz = TaNDD.class)
public String getIdTitulaire() {
	return idTitulaire;
}



public void setIdTitulaire(String idTitulaire) {
	this.idTitulaire = idTitulaire;
}



@Column(name = "PASSEWORD", length = 100)
@LgrHibernateValidated(champ = "PASSEWORD",table = "TA_NDD",clazz = TaNDD.class)
public String getPasseword() {
	return passeword;
}



public void setPasseword(String passeword) {
	this.passeword = passeword;
}



@Column(name = "QUESTION", length = 255)
@LgrHibernateValidated(champ = "QUESTION",table = "TA_NDD",clazz = TaNDD.class)
public String getQuestion() {
	return question;
}



public void setQuestion(String question) {
	this.question = question;
}



@Column(name = "REPONSE", length = 255)
@LgrHibernateValidated(champ = "REPONSE",table = "TA_NDD",clazz = TaNDD.class)
public String getReponse() {
	return reponse;
}



public void setReponse(String reponse) {
	this.reponse = reponse;
}



@Column(name = "AUTH_INFO", length = 100)
@LgrHibernateValidated(champ = "AUTH_INFO",table = "TA_NDD",clazz = TaNDD.class)
public String getAuthInfo() {
	return authInfo;
}



public void setAuthInfo(String authInfo) {
	this.authInfo = authInfo;
}

	


}
