package fr.legrain.gestCom.Module_Document;

// Generated 20 mars 2007 09:51:19 by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;

import fr.legrain.documents.dao.TaAcompte;
import fr.legrain.documents.dao.TaApporteur;
import fr.legrain.documents.dao.TaAvoir;
import fr.legrain.documents.dao.TaBoncde;
import fr.legrain.documents.dao.TaBonliv;
import fr.legrain.documents.dao.TaDevis;
import fr.legrain.documents.dao.TaFacture;
import fr.legrain.documents.dao.TaProforma;
import fr.legrain.documents.dao.TaRAcompte;
import fr.legrain.documents.dao.TaTPaiement;
import fr.legrain.lib.data.LgrConstantes;
import fr.legrain.lib.data.ModelObject;
import fr.legrain.tiers.dao.TaCompteBanque;

/**
 * IHMEnteteFacture generated by hbm2java
 */
public class IHMEtat extends ModelObject {

	
	public static int insertion=1<<2; //4
	public static int edition=1<<3; //8
	public static int suppression=1<<4; //16
	public static int enregistrer=1<<5; //32
	public static int integre=1<<6; //64
	public static int multiple=1<<7; //128
	
	public IHMEtat() {
	}
	
	



}
