package fr.legrain.departement.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.gestCom.Appli.LgrHibernateValidated;


/**
 * TaDepartements generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_DEPARTEMENTS")

public class TaDepartements implements java.io.Serializable {
	


	private int numDep;
	private String codeDep;
	private String nomDep;
	private String codeRegion;
	private String nomRegion;

	public TaDepartements() {
	}

	public TaDepartements(int idAdresse) {
		this.numDep = numDep;
	}

	public TaDepartements(int numDep, String codeDep, String nomDep,
			String codeRegion, String nomRegion) {
		this.numDep = numDep;
		this.codeDep = codeDep;
		this.nomDep = nomDep;
		this.codeRegion = codeRegion;
		this.nomRegion = nomRegion;

	}
	@Id
	@Column(name = "NUMDEP", unique = true, nullable = false)
	public int getNumDep() {
		return numDep;
	}

	public void setNumDep(int numDep) {
		this.numDep = numDep;
	}

	
	@Column(name = "CODEDEP", nullable = false)
	public String getCodeDep() {
		return codeDep;
	}

	public void setCodeDep(String codeDep) {
		this.codeDep = codeDep;
	}

	@Column(name = "NOMDEP", nullable = false)
	public String getNomDep() {
		return nomDep;
	}

	public void setNomDep(String nomDep) {
		this.nomDep = nomDep;
	}

	@Column(name = "CODEREGION", nullable = false)
	public String getCodeRegion() {
		return codeRegion;
	}

	public void setCodeRegion(String codeRegion) {
		this.codeRegion = codeRegion;
	}

	@Column(name = "NOMREGION", nullable = false)
	public String getNomRegion() {
		return nomRegion;
	}

	public void setNomRegion(String nomRegion) {
		this.nomRegion = nomRegion;
	}


}
