package fr.legrain.changelog.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-11-20T14:23:46.114+01:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://dev.changelog.fr/ws/changelogApi/1.0/", name = "changelogApiPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ChangelogApiPortType {

    @WebResult(name = "return", targetNamespace = "http://dev.changelog.fr/ws/changelogApi/1.0/", partName = "return")
    @WebMethod(action = "http://dev.changelog.fr/ws/changelogApi/1.0/get")
    public Category get(
        @WebParam(partName = "idcategory", name = "idcategory")
        int idcategory
    );
}
