package fr.legrain.pointLgr.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import sun.security.util.BigInt;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.stocks.dao.TaStock;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_ARTICLE_POINT")
@SequenceGenerator(name = "GEN_ARTICLE_POINT", sequenceName = "NUM_ID_ARTICLE_POINT", allocationSize = 1)
public class TaArticlePoint implements java.io.Serializable {

	private int idArticlePoint;
	private Date debutPeriode;
	private Date finPeriode;
	private BigDecimal points;
	private BigDecimal prixReference;
	private TaArticle taArticle;
	private Integer indice = 0;
	private String quiCree;
	private Date quandCree;
	private String quiModif;
	private Date quandModif;
	private String ipAcces;
	private Integer versionObj;
	private String version;
	private TaTypeMouvPoint taTypeMouvPoint;

	public TaArticlePoint() {
	}

	public TaArticlePoint(int idArticlePoint) {
		this.idArticlePoint = idArticlePoint;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_ARTICLE_POINT")
	@Column(name = "ID_ARTICLE_POINT", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_ARTICLE_POINT",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public int getIdArticlePoint() {
		return this.idArticlePoint;
	}

	public void setIdArticlePoint(int idArticlePoint) {
		this.idArticlePoint = idArticlePoint;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade ={CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champ = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return this.taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "DEBUT_PERIODE", length = 19)
	@LgrHibernateValidated(champ = "DEBUT_PERIODE",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public Date getDebutPeriode() {
		return this.debutPeriode;
	}

	public void setDebutPeriode(Date debutPeriode) {
		this.debutPeriode = debutPeriode;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FIN_PERIODE", length = 19)
	@LgrHibernateValidated(champ = "FIN_PERIODE",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public Date getFinPeriode() {
		return this.finPeriode;
	}

	public void setFinPeriode(Date finPeriode) {
		this.finPeriode = finPeriode;
	}
	
	@Column(name = "POINTS", precision = 15)
	@LgrHibernateValidated(champ = "POINTS",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public BigDecimal getPoints() {
		return this.points;
	}

	public void setPoints(BigDecimal points) {
		this.points = points;
	}
	
	@Column(name = "PRIX_REFERENCE", precision = 15)
	@LgrHibernateValidated(champ = "PRIX_REFERENCE",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public BigDecimal getPrixReference() {
		return this.prixReference;
	}

	public void setPrixReference(BigDecimal prixReference) {
		this.prixReference = prixReference;
	}
	
	@Column(name = "QUI_CREE", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCree) {
		this.quiCree = quiCree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCree) {
		this.quandCree = quandCree;
	}

	@Column(name = "QUI_MODIF", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModif) {
		this.quiModif = quiModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModif) {
		this.quandModif = quandModif;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}

	@Column(name = "INDICE")
	@LgrHibernateValidated(champ = "INDICE",table = "TA_ARTICLE_POINT",clazz = TaArticlePoint.class)
	public Integer getIndice() {
		return indice;
	}

	public void setIndice(Integer indice) {
		this.indice = indice;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade ={CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_TYPE_MOUV")
	@LgrHibernateValidated(champ = "ID_TYPE_MOUV",table = "TYPE_MOUV_POINT_BONUS",clazz = TaTypeMouvPoint.class)
	public TaTypeMouvPoint getTaTypeMouvPoint() {
		return taTypeMouvPoint;
	}

	public void setTaTypeMouvPoint(TaTypeMouvPoint taTypeMouvPoint) {
		this.taTypeMouvPoint = taTypeMouvPoint;
	}


}
