package fr.legrain.pointLgr.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.sun.org.apache.bcel.internal.generic.NEW;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.documents.dao.TaAvisEcheance;
import fr.legrain.documents.dao.TaFacture;
import fr.legrain.documents.dao.TaRAcompte;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.stocks.dao.TaStock;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaComptePoint generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "COMPTE_POINT_BONUS")
@SequenceGenerator(name = "GEN_COMPTE_POINT", sequenceName = "NUM_ID_COMPTEPOINTBONUS", allocationSize = 1)
public class TaComptePoint implements java.io.Serializable {
	public static final String TYPE_DOC = "fr.legrain.pointsBonus";
	private int idPoint;
	private BigDecimal point;
	private Date dateAcquisition;
	private Date datePeremption;
	private Date dateUtilisation;
	private String version;
	private TaTiers taTiers;
	private String codeDocument;
	private TaTypeMouvPoint taTypeMouvPoint;
	private String commentaire;
	
	private BigDecimal utilise_avis=new BigDecimal(0);
	private BigDecimal utilise_facture=new BigDecimal(0);
	
	private String ipAcces;
	private Integer versionObj;
	@Transient
	private String libelleEtat;
	@Transient
	private TaAvisEcheance taAvisEcheance;
	
	public TaComptePoint() {
	}

	public TaComptePoint(int idPoint) {
		this.idPoint = idPoint;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_COMPTE_POINT")
	@Column(name = "ID_POINT", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_POINT",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public int getIdPoint() {
		return this.idPoint;
	}

	public void setIdPoint(int idTiersPoint) {
		this.idPoint = idTiersPoint;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade ={CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_TIERS")
	@LgrHibernateValidated(champ = "ID_TIERS",table = "TA_TIERS",clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return this.taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinColumn(name = "ID_TYPE_MOUV")
	@LgrHibernateValidated(champ = "ID_TYPE_MOUV",table = "TYPE_MOUV_POINT_BONUS",clazz = TaTypeMouvPoint.class)
	public TaTypeMouvPoint getTaTypeMouvPoint() {
		return taTypeMouvPoint;
	}

	public void setTaTypeMouvPoint(TaTypeMouvPoint taTypeMouvPoint) {
		this.taTypeMouvPoint = taTypeMouvPoint;
	}


	@Column(name = "POINT", precision = 15)
	@LgrHibernateValidated(champ = "POINT",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public BigDecimal getPoint() {
		return this.point;
	}

	public void setPoint(BigDecimal points) {
		this.point = points;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PEREMPTION", length = 19)
	@LgrHibernateValidated(champ = "DATE_PEREMPTION",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public Date getDatePeremption() {
		return this.datePeremption;
	}

	public void setDatePeremption(Date dateValidite) {
		this.datePeremption = dateValidite;
	}
	
	@Column(name = "CODE_DOCUMENT", length = 9)
	@LgrHibernateValidated(champ = "CODE_DOCUMENT",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public String getCodeDocument() {
		return codeDocument;
	}

	public void setCodeDocument(String codeDocument) {
		this.codeDocument = codeDocument;
	}

	
	
	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}




	@Column(name = "COMMENTAIRE", length = 2000)
	@LgrHibernateValidated(champ = "COMMENTAIRE",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public String getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ACQUISITION", length = 19)
	@LgrHibernateValidated(champ = "DATE_ACQUISITION",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public Date getDateAcquisition() {
		return dateAcquisition;
	}

	public void setDateAcquisition(Date dateAcquisition) {
		this.dateAcquisition = dateAcquisition;
	}

	
	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_UTILISATION", length = 19)
	@LgrHibernateValidated(champ = "DATE_UTILISATION",table = "COMPTE_POINT_BONUS",clazz = TaComptePoint.class)
	public Date getDateUtilisation() {
		return dateUtilisation;
	}

	public void setDateUtilisation(Date dateUtilisation) {
		this.dateUtilisation = dateUtilisation;
	}

	@Transient
	public TaAvisEcheance getTaAvisEcheance() {
		return taAvisEcheance;
	}

	@Transient
	public void setTaAvisEcheance(TaAvisEcheance taAvisEcheance) {
		this.taAvisEcheance = taAvisEcheance;
	}

	@Transient
	public String getLibelleEtat() {
		return libelleEtat;
	}
	@Transient
	public void setLibelleEtat(String libelleEtat) {
		this.libelleEtat = libelleEtat;
	}

	public BigDecimal getUtilise_avis() {
		return utilise_avis;
	}

	public void setUtilise_avis(BigDecimal utilise_avis) {
		this.utilise_avis = utilise_avis;
	}

	public BigDecimal getUtilise_facture() {
		return utilise_facture;
	}

	public void setUtilise_facture(BigDecimal utilise_facture) {
		this.utilise_facture = utilise_facture;
	}




}
