package fr.legrain.pointLgr.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import sun.security.util.BigInt;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.stocks.dao.TaStock;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_INDICE_POINT")
@SequenceGenerator(name = "GEN_INDICE_POINT", sequenceName = "NUM_ID_INDICE_POINT", allocationSize = 1)
public class TaIndicePoint implements java.io.Serializable {

	private int idIndicePoint;
	private BigDecimal points;
	private BigDecimal tranche;
	private Integer nbProduit;
	private String quiCree;
	private Date quandCree;
	private String quiModif;
	private Date quandModif;
	private String ipAcces;
	private Integer versionObj;
	private String version;

	public TaIndicePoint() {
	}

	public TaIndicePoint(int idIndicePoint) {
		this.idIndicePoint = idIndicePoint;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_INDICE_POINT")
	@Column(name = "ID_INDICE_POINT", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_INDICE_POINT",table = "TA_INDICE_POINT",clazz = TaIndicePoint.class)
	public int getIdIndicePoint() {
		return this.idIndicePoint;
	}

	public void setIdIndicePoint(int idIndicePoint) {
		this.idIndicePoint = idIndicePoint;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}	
	
	@Column(name = "POINTS", precision = 15)
	@LgrHibernateValidated(champ = "POINTS",table = "TA_INDICE_POINT",clazz = TaIndicePoint.class)
	public BigDecimal getPoints() {
		return this.points;
	}

	public void setPoints(BigDecimal points) {
		this.points = points;
	}
	

	@Column(name = "TRANCHE", precision = 15)
	@LgrHibernateValidated(champ = "TRANCHE",table = "TA_INDICE_POINT",clazz = TaIndicePoint.class)
	public BigDecimal getTranche() {
		return this.tranche;
	}

	public void setTranche(BigDecimal tranche) {
		this.tranche = tranche;
	}
	
	@Column(name = "NB_PRODUIT")
	@LgrHibernateValidated(champ = "NB_PRODUIT",table = "TA_INDICE_POINT",clazz = TaIndicePoint.class)
	public Integer getNbProduit() {
		return nbProduit;
	}

	public void setNbProduit(Integer nbProduit) {
		this.nbProduit = nbProduit;
	}
	
	@Column(name = "QUI_CREE", length = 50)
	public String getQuiCree() {
		return this.quiCree;
	}

	public void setQuiCree(String quiCree) {
		this.quiCree = quiCree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_CREE", length = 19)
	public Date getQuandCree() {
		return this.quandCree;
	}

	public void setQuandCree(Date quandCree) {
		this.quandCree = quandCree;
	}

	@Column(name = "QUI_MODIF", length = 50)
	public String getQuiModif() {
		return this.quiModif;
	}

	public void setQuiModif(String quiModif) {
		this.quiModif = quiModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "QUAND_MODIF", length = 19)
	public Date getQuandModif() {
		return this.quandModif;
	}

	public void setQuandModif(Date quandModif) {
		this.quandModif = quandModif;
	}

	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}








}
