package fr.legrain.pointLgr.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.stocks.dao.TaStock;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "POINTACQUISANNEE")
@SequenceGenerator(name = "GEN_POINTACQUIS", sequenceName = "NUM_ID_POINTACQUIS", allocationSize = 1)
public class TaPointAcquisAnnee implements java.io.Serializable {

	private int idPoint;
	private Date datePeremption;//DATE_PEREMPTION
	private TaTiers taTiers;//ID_TIERS
	private BigDecimal points;//POINTS
	private Integer historique;//HISTORIQUE
	private String codeDocument;//CODE_FACTURE
	private String ipAcces;
	private Integer versionObj;
	private String version;

	public TaPointAcquisAnnee() {
	}

	public TaPointAcquisAnnee(int idPoint) {
		this.idPoint = idPoint;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_POINTACQUIS")
	@Column(name = "ID_POINT", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_POINT",table = "POINTACQUISANNEE",clazz = TaPointAcquisAnnee.class)
	public int getIdPoint() {
		return this.idPoint;
	}

	public void setIdPoint(int idArticleAccPoint) {
		this.idPoint = idArticleAccPoint;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "POINTS", precision = 15)
	@LgrHibernateValidated(champ = "POINTS",table = "POINTACQUISANNEE",clazz = TaPointAcquisAnnee.class)
	public BigDecimal getPoints() {
		return points;
	}

	public void setPoints(BigDecimal points) {
		this.points = points;
	}

	@Column(name = "HISTORIQUE")
	@LgrHibernateValidated(champ = "HISTORIQUE",table = "POINTACQUISANNEE",clazz = TaPointAcquisAnnee.class)
	public Integer getHistorique() {
		return historique;
	}

	public void setHistorique(Integer historique) {
		this.historique = historique;
	}

	@Column(name = "CODE_DOCUMENT", length = 9)
	@LgrHibernateValidated(champ = "CODE_DOCUMENT",table = "POINTACQUISANNEE",clazz = TaPointAcquisAnnee.class)
	public String getCodeDocument() {
		return codeDocument;
	}

	public void setCodeDocument(String codeDocument) {
		this.codeDocument = codeDocument;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TIERS")
	@LgrHibernateValidated(champ = "ID_TIERS",table = "TA_TIERS",clazz = TaTiers.class)
	public TaTiers getTaTiers() {
		return this.taTiers;
	}

	public void setTaTiers(TaTiers taTiers) {
		this.taTiers = taTiers;
	}


	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PEREMPTION", length = 19)
	@LgrHibernateValidated(champ = "DATE_PEREMPTION",table = "POINTACQUISANNEE",clazz = TaPointAcquisAnnee.class)
	public Date getDatePeremption() {
		return this.datePeremption;
	}

	public void setDatePeremption(Date debutPeriode) {
		this.datePeremption = debutPeriode;
	}
	
	
	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}




}
