package fr.legrain.pointLgr.dao;

// Generated Mar 24, 2009 4:44:04 PM by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.articles.dao.TaArticle;
import fr.legrain.documents.dao.TaFacture;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.stocks.dao.TaStock;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaAdresse generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TYPE_MOUV_POINT_BONUS")
@SequenceGenerator(name = "GEN_TYPE_MOUV", sequenceName = "NUM_ID_TYPE_MOUV_POINT", allocationSize = 1)
public class TaTypeMouvPoint implements java.io.Serializable {

	private int idTypeMouv;
	private String version;
	private String libelleMouv;
	private String typeMouv;

	private TaArticle taArticle;
	private String ipAcces;
	private Integer versionObj;

	public TaTypeMouvPoint() {
	}

	public TaTypeMouvPoint(int idTypeMouv) {
		this.idTypeMouv = idTypeMouv;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_TYPE_MOUV")
	@Column(name = "ID_TYPE_MOUV", unique = true, nullable = false)
	@LgrHibernateValidated(champ = "ID_TYPE_MOUV",table = "TYPE_MOUV_POINT_BONUS",clazz = TaTypeMouvPoint.class)
	public int getIdTypeMouv() {
		return this.idTypeMouv;
	}

	public void setIdTypeMouv(int idTypeMouv) {
		this.idTypeMouv = idTypeMouv;
	}

	@Column(name = "VERSION", length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}


	
	@Column(name = "TYPE_MOUV", length = 2)
	@LgrHibernateValidated(champ = "TYPE_MOUV",table = "TYPE_MOUV_POINT_BONUS",clazz = TaTypeMouvPoint.class)
	public String getTypeMouv() {
		return typeMouv;
	}

	public void setTypeMouv(String typeMouv) {
		this.typeMouv = typeMouv;
	}

	@Column(name = "LIBELLE_MOUV", length = 100)
	@LgrHibernateValidated(champ = "LIBELLE_MOUV",table = "TYPE_MOUV_POINT_BONUS",clazz = TaTypeMouvPoint.class)
	public String getLibelleMouv() {
		return libelleMouv;
	}

	public void setlibelleMouv(String libelleMouv) {
		this.libelleMouv = libelleMouv;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_ARTICLE")
	@LgrHibernateValidated(champ = "ID_ARTICLE",table = "TA_ARTICLE",clazz = TaArticle.class)
	public TaArticle getTaArticle() {
		return this.taArticle;
	}

	public void setTaArticle(TaArticle taArticle) {
		this.taArticle = taArticle;
	}

	
	@Column(name = "IP_ACCES", length = 50)
	public String getIpAcces() {
		return this.ipAcces;
	}

	public void setIpAcces(String ipAcces) {
		this.ipAcces = ipAcces;
	}

	@Version
	@Column(name = "VERSION_OBJ")
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}








}
