package fr.legrain.SupportAbonLegrain.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_REGISTRAR")
@SequenceGenerator(name = "GEN_REGISTRAR", sequenceName = "NUM_ID_REGISTRAR", allocationSize = 1)

public class TaRegistrar implements java.io.Serializable {
    
	private Integer idRegistrar;
	private String registrar;


	
	public TaRegistrar() {
	}

	public TaRegistrar(Integer idRegistrar) {
		this.idRegistrar = idRegistrar;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_REGISTRAR")
	@Column(name = "ID_REGISTRAR", unique = true)
	public Integer getIdRegistrar() {
		return this.idRegistrar;
	}

	public void setIdRegistrar(Integer idRegistrar) {
		this.idRegistrar = idRegistrar;
	}

	@Column(name = "REGISTRAR")
	@LgrHibernateValidated(champ = "REGISTRAR",table = "TA_REGISTRAR",clazz = TaRegistrar.class)
	public String getRegistrar() {
		return this.registrar;
	}

	public void setRegistrar(String registrar) {
		this.registrar = registrar;
	}
	
	
	
}
