package fr.legrain.SupportAbonLegrain.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import fr.legrain.abonnement.dao.TaAbonnement;
import fr.legrain.abonnement.dao.TaRAbonnement;
import fr.legrain.articles.dao.TaArticle;
import fr.legrain.articles.dao.TaTSupport;
import fr.legrain.documents.dao.TaLFacture;
import fr.legrain.documents.dao.TaRDocument;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_R_IP_FIXE")
@SequenceGenerator(name = "GEN_R_IP_FIXE", sequenceName = "NUM_ID_R_IP_FIXE", allocationSize = 1)

public  class TaRIpFixe implements java.io.Serializable {

   
	private Integer idRIpFixe;
    private TaIpFixe taIpFixe;
    private TaServeur taServeur;
	
    
	public TaRIpFixe() {
	}

	public TaRIpFixe(Integer idROptionAbon) {
		this.idRIpFixe = idROptionAbon;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_R_IP_FIXE")
	@Column(name = "ID_R_IP_FIXE", unique = true)
	public Integer getIdIpFixe() {
		return this.idRIpFixe;
	}

	public void setIdIpFixe(Integer idRIpFixe) {
		this.idRIpFixe = idRIpFixe;
	}

	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_IP_FIXE")
	@LgrHibernateValidated(champ = "ID_IP_FIXE",table = "TA_IP_FIXE",clazz = TaIpFixe.class)
	public TaIpFixe getTaIpFixe() {
		return taIpFixe;
	}

	public void setTaIpFixe(TaIpFixe taIpFixe) {
		this.taIpFixe = taIpFixe;
	}


	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "ID_SERVEUR")
	@LgrHibernateValidated(champ = "ID_SERVEUR",table = "TA_SERVEUR",clazz = TaServeur.class)
	public TaServeur getTaServeur() {
		return taServeur;
	}

	public void setTaServeur(TaServeur taServeur) {
		this.taServeur = taServeur;
	}
	
	
}
