package fr.legrain.SupportAbonLegrain.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_SERVEUR")
@SequenceGenerator(name = "GEN_SERVEUR", sequenceName = "NUM_ID_SERVEUR", allocationSize = 1)

public class TaServeur implements java.io.Serializable {
    
	private Integer idServeur;
	private String serveur;


	
	public TaServeur() {
	}

	public TaServeur(Integer idServeur) {
		this.idServeur = idServeur;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_SERVEUR")
	@Column(name = "ID_SERVEUR", unique = true)
	public Integer getIdServeur() {
		return this.idServeur;
	}

	public void setIdServeur(Integer idServeur) {
		this.idServeur = idServeur;
	}

	@Column(name = "SERVEUR")
	@LgrHibernateValidated(champ = "SERVEUR",table = "TA_SERVEUR",clazz = TaServeur.class)
	public String getServeur() {
		return this.serveur;
	}

	public void setServeur(String serveur) {
		this.serveur = serveur;
	}
	
	
	
}
