package fr.legrain.SupportAbonLegrain.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import fr.legrain.articles.dao.TaArticle;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
//@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "TA_UTILISATEUR")
@SequenceGenerator(name = "GEN_UTILISATEUR", sequenceName = "NUM_ID_UTILISATEUR", allocationSize = 1)

public class TaUtilisateur implements java.io.Serializable {
    
	private Integer idUtilisateur;
	private String nom;
    private String prenom;
    private String tel;
    private String email;
	private Integer versionObj;
//    private Set<TaLicence> taLicences = new HashSet<TaLicence>(0);

	
	public TaUtilisateur() {
	}

	public TaUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}


	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "GEN_UTILISATEUR")
	@Column(name = "ID_UTILISATEUR", unique = true)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "NOM")
	@LgrHibernateValidated(champ = "NOM",table = "TA_UTILISATEUR",clazz = TaUtilisateur.class)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}
	@Column(name = "PRENOM")
	@LgrHibernateValidated(champ = "PRENOM",table = "TA_UTILISATEUR",clazz = TaUtilisateur.class)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}
	
	@Column(name = "TEL")
	@LgrHibernateValidated(champ = "TEL",table = "TA_UTILISATEUR",clazz = TaUtilisateur.class)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}
	
	@Column(name = "EMAIL")
	@LgrHibernateValidated(champ = "EMAIL",table = "TA_UTILISATEUR",clazz = TaUtilisateur.class)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Version
	@Column(name = "VERSION_OBJ", precision = 15)
	public Integer getVersionObj() {
		return this.versionObj;
	}

	public void setVersionObj(Integer versionObj) {
		this.versionObj = versionObj;
	}	
}
