package fr.legrain.antiVirus.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_ANTI_VIRUS")
public  class TaAntiVirus extends TaSupportAbon implements java.io.Serializable {

	
	public TaAntiVirus() {
	}





}
