package fr.legrain.supportImmosManager.dao;

// Generated 11 août 2009 15:52:23 by Hibernate Tools 3.2.4.GA

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.legrain.SupportAbon.dao.TaSupportAbon;
import fr.legrain.SupportAbonLegrain.dao.TaUtilisateur;
import fr.legrain.gestCom.Appli.LgrHibernateValidated;
import fr.legrain.tiers.dao.TaFamilleTiers;


/**
 * TaWlgr generated by hbm2java
 */
@Entity
@Table(name = "TA_IMMOS_MANAGEUR")
public  class TaImmosManager extends TaSupportAbon implements java.io.Serializable {

	private TaUtilisateur taUtilisateur;
    private TaFamilleTiers groupe;
	
	public TaImmosManager() {
	}

	


	
	public TaImmosManager(TaUtilisateur taUtilisateur, TaFamilleTiers groupe) {
		super();
		this.taUtilisateur = taUtilisateur;
		this.groupe = groupe;
	}





	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "ID_UTILISATEUR")
	@LgrHibernateValidated(champ = "ID_UTILISATEUR",table = "TA_UTILISATEUR",clazz = TaUtilisateur.class)
	public TaUtilisateur getTaUtilisateur() {
		return taUtilisateur;
	}

	public void setTaUtilisateur(TaUtilisateur taUtilisateur) {
		this.taUtilisateur = taUtilisateur;
	}

	
	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.REFRESH)
	@JoinColumn(name = "GROUPE")
	@LgrHibernateValidated(champ = "ID_FAMILLE",table = "TA_FAMILLE_TIERS",clazz = TaFamilleTiers.class)
	public TaFamilleTiers getGroupe() {
		return groupe;
	}

	public void setGroupe(TaFamilleTiers groupe) {
		this.groupe = groupe;
	}
	

	


}
